version: '3'

tasks:

  build-internal:
    internal: true
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - "CGO_ENABLED={{.CGO_ENABLED}} GOOS={{.GOOS}} GOARCH={{.GOARCH}} /bin/sh scripts/build_services.sh"

  build:
    vars:
      CGO_ENABLED:
        sh: go env CGO_ENABLED
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - task: build-internal
        vars:
          CGO_ENABLED: "{{.CGO_ENABLED}}"
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.GOARCH}}"

  build-linux:
    cmds:
      - task: build-internal
        vars:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64

  init:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - "go install tool"
      - "easyp mod update"
      - "easyp mod vendor"
      - "easyp generate"

  #TODO: как-то заставить его выполнять действия по порядку!!!
  up:
    dir: '{{.USER_WORKING_DIR}}'
    deps:
      - "init"
      - "build-linux"
    dotenv:
      - ".env"
    preconditions:
      - "test -f docker-compose.yml"
    cmds:
      - "docker compose up --build --remove-orphans --detach"

  down:
    dir: '{{.USER_WORKING_DIR}}'
    dotenv:
      - ".env"
    preconditions:
      - "test -f docker-compose.yml"
    cmds:
      - "docker compose down --volumes"

  clear:
    desc: "Очистка сгенерированных файлов (.pb.*), vendor, бинарников и lock/sum файлов"
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - "find api -type f -name '*.pb.*' -delete 2>/dev/null || true"
      - "rm -rf easyp_vendor"
      - "rm -rf services/*/bin"
      - "rm -f easyp.lock"
      - "find . -type f -name 'go.sum' -delete 2>/dev/null || true"
      - "find . -type f -name 'go.work.sum' -delete 2>/dev/null || true"
